const DISPLAY_ALERT= 'SHOW_ALERT';
const CLEAR_ALERT='CLEAR_ALERT';
const REGISTER_USER_BEGIN= 'REGISTER_USER_BEGIN';
const REGISTER_USER_SUCCESS= 'REGISTER_USER_SUCCESS';
const REGISTER_USER_ERROR= 'REGISTER_USER_ERROR';

const LOGIN_USER_BEGIN= 'LOGIN_USER_BEGIN';
const LOGIN_USER_SUCCESS= 'LOGIN_USER_SUCCESS';
const LOGIN_USER_ERROR= 'LOGIN_USER_ERROR';

const TOGGLE_SIDEBAR= 'TOGGLE_SIDEBAR';
const LOGOUT_USER= 'LOGOUT_USER';

const UPDATE_USER_BEGIN= 'UPDATE_USER_BEGIN';
const UPDATE_USER_SUCCESS= 'UPDATE_USER_SUCCESS';
const UPDATE_USER_ERROR='UPDATE_USER_ERROR'

export const CLEAR_VALUES= 'CLEAR_VALUES'
export const HANDLE_CHANGE='HANDLE_CHANGE'

export const CREATE_CLIENT_BEGIN='CREATE_CLIENT_BEGIN';
export const CREATE_CLIENT_SUCCESS='CREATE_CLIENT_SUCCESS';
export const CREATE_CLIENT_ERROR='CREATE_CLIENT_ERROR';

export const GET_CLIENTS_BEGIN='GET_CLIENTS_BEGIN';
export const GET_CLIENTS_SUCCESS='GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_ERROR= 'GET_CLIENTS_ERROR';

export const LOAN_START='LOAN_START';

export const CREATE_LOAN_START='CREATE_LOAN_START'
export const CREATE_LOAN_SUCCESS='CREATE_LOAN_SUCESS';
export const CREATE_LOAN_ERROR='CREATE_LOAN_ERROR';

export const CANCEL_LOAN_SUBMIT='CANCEL_LOAN_SUBMIT';

export const HANDLE_LOAN_CHANGE='HANDLE_LOAN_CHANGE';

export const DELETE_CLIENT_BEGIN='DELETE_CLIENT_BEGIN';
export const DELETE_CLIENT_SUCCESS='DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_ERROR='DELETE_CLIENT_ERROR';

export const SHOW_STATS_BEGIN='SHOW_STATS_BEGIN';
export const SHOW_STATS_SUCCESS='SHOW_STATS_SUCCESS';

export const CLEAR_FILTERS= 'CLEAR_FILTERS';

export const CHANGE_PAGE= 'CHANGE_PAGE';

export const GET_CLIENT_START='GET_CLIENT_START';
export const GET_CLIENT_SUCCESS='GET_CLIENT_SUCCESS';

export const CLEAR_CLIENT_DATA='CLEAR_CLIENT_DATA';

export const DISBURSE_LOAN_START='DISBURSE_LOAN_START';
export const DISBURSE_LOAN_SUCESS='DISBURSE_LOAN_SUCCESS';

export const WRITE_OFF_START= 'WRITE_OFF_START';
export const WRITE_OFF_SUCESS='WRITE_OFF_SUCCESS';

export const DEFAULT_START='DEFAULT_START';
export const DEFAULT_SUCCESS='DEFAULT_SUCCESS';

export const REJECT_LOAN_START= 'REJECT_LOAN_START';
export const REJECT_LOANL_SUCCESS='REJECT_LOAN_SUCCESS';

export const GIVE_MONEY_START='GIVE_MONEY_START';
export const GIVE_MONEY_SUCCESS='GIVE_MONEY_SUCCESS'

export {DISPLAY_ALERT,CLEAR_ALERT,LOGOUT_USER,UPDATE_USER_BEGIN,UPDATE_USER_ERROR,UPDATE_USER_SUCCESS,TOGGLE_SIDEBAR,LOGIN_USER_BEGIN,LOGIN_USER_ERROR,LOGIN_USER_SUCCESS,REGISTER_USER_BEGIN,REGISTER_USER_SUCCESS,REGISTER_USER_ERROR};